---
- name: "Digest splited blob list var"
  include_vars: blob_vars.yml
  when: nexus_blob_split | bool

- name: Create Nexus backup directory
  file:
    path: "{{ nexus_backup_dir }}"
    state: "directory"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
  when: nexus_backup_dir_create | bool

- import_tasks: nexus_config_pre_admin_user.yml
- import_tasks: nexus_config_pre_register_script.yml
