---
- name: Change admin password if we are still using default
  block:
    - include_tasks: call_script.yml
      vars:
        script_name: update_admin_password
        args:
          new_password: "{{ nexus_admin_password }}"

    - name: Admin password changed
      set_fact:
        current_nexus_admin_password: "{{ nexus_admin_password }}"
      no_log: true

    - name: Clear generated password file from install (nexus > 3.17)
      file:
        path: "{{ nexus_admin_password_path }}"
        state: absent

  when: (nexus_api_head_with_default_password.status | default(false)) == 200
